### ISSUE TITLE
future maintenance and collaboration

### ISSUE THREAD

**Issue by anarcat** [NTTCom-MS/eyp-bacula#9]
Hi!

This module is one out of [about 10 bacula modules on Puppet Forge](https://forge.puppet.com/modules?q=bacula). It is [third in rank](https://forge.puppet.com/modules?utf-8=%E2%9C%93&page_size=25&sort=rank&q=bacula) and [third in downloads](https://forge.puppet.com/modules?q=bacula&page_size=25&sort=downloads), but it hasn't seen a release in over a year. Is the module going to be maintained in the future?

How does this module compare with the other Bacula modules in the forge? Why would someone pick this one instead of the others? When the module was created the [Puppetlabs/Vox Populi module](https://forge.puppet.com/puppetlabs/bacula) already, as did the [zleslie one](https://github.com/xaque208/puppet-bacula). Why did you feel the need to create a third one? :)

Is there a possibility of converging efforts towards a single module that everyone contributes to?

Thanks for any clarification and thank you for sharing your code publicly! :)

**Comment by anarcat** [comment]
Note that I have filed a similar issue in the other two module, in the hope some future collaboration will emerge (https://github.com/voxpupuli/puppet-bacula/issues/47 https://github.com/xaque208/puppet-bacula/issues/136).

**Comment by jordiprats** [comment]
Hi,
I haven't updated this module since it covers all my needs so far. I chose to create a new module because I felt the way the others worked didn't match how I feel it should work

I'd welcome any contributions, and thanks for your interest. Cheers.
